# These are supported funding model platforms

# Preencha apenas o que usar. Os demais podem ficar comentados.

# github: [user1, user2, user3, user4]
# patreon: username
# open_collective: project
# ko_fi: username
# tidelift: platform-name/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# lfx_crowdfunding: project-name
# polar: username
# buy_me_a_coffee: username
# thanks_dev: username

# Links personalizados (pode ter mais de um)
custom:
  - https://link.mercadopago.com.br/contribuirprojeto1
